import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from config import EMAIL_USER, EMAIL_PASS
# email_service.py

# ... (keep your existing send_email and send_portfolio_email functions)

def send_transaction_notification(to_email, coin, action, amount):
    """Sends a professional receipt after a Buy or Sell transaction."""
    subject = f"📝 Transaction Confirmation: {action} {coin}"
    color = "#00ffcc" if action == "Buy" else "#ff4b4b"
    
    html = f"""
    <html>
    <body style="font-family:Arial;background:#0f0c29;color:white;padding:20px;">
        <h2 style="color:{color};">{action} Order Confirmed</h2>
        <div style="background:#302b63;padding:20px;border-radius:10px;border-left:5px solid {color};">
            <p><b>Asset:</b> {coin}</p>
            <p><b>Amount:</b> ${amount:,.2f}</p>
            <p><b>Status:</b> Completed</p>
        </div>
        <p style="color:#94A3B8;font-size:12px;margin-top:20px;">Receipt generated by CryptoPort AI.</p>
    </body>
    </html>
    """
    return send_email(to_email, subject, html)
def send_email(to_email: str, subject: str, html_content: str):
    try:
        msg = MIMEMultipart()
        msg["From"] = EMAIL_USER
        msg["To"] = to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(html_content, "html"))

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print("Email Error:", e)
        return False

# NEW: Transaction Receipt Function
def send_transaction_notification(to_email, coin, action, amount):
    subject = f"📝 Transaction Confirmation: {action} {coin}"
    color = "#00ffcc" if action == "Buy" else "#ff4b4b"
    
    html = f"""
    <html>
    <body style="font-family:Arial;background:#0f0c29;color:white;padding:20px;">
        <h2 style="color:{color};">{action} Order Confirmed</h2>
        <div style="background:#302b63;padding:20px;border-radius:10px;border-left:5px solid {color};">
            <p><b>Asset:</b> {coin}</p>
            <p><b>Amount:</b> ${amount:,.2f}</p>
            <p><b>Status:</b> Success</p>
        </div>
        <p style="color:#94A3B8;font-size:12px;margin-top:20px;">This is an automated receipt for your CryptoPort AI account.</p>
    </body>
    </html>
    """
    return send_email(to_email, subject, html)

# Existing function renamed for clarity
def send_portfolio_summary_email(to_email, portfolio_df):
    # (Keep your existing summary table logic here)
    pass
